//! Bounded download/cache contracts for offline media.
//!
//! These types implement the source-scoped offline media contract
//! documented in `docs/offline-media.md` (P3.1). The contract requires:
//!
//! - The download/cache engine never becomes a source of its own. Cached
//!   items are owned by an existing `Source` and identified by the same
//!   `(SourceId, TrackId)` pair used by live playback.
//! - Offline capability is default-deny and source-scoped:
//!   `offline_snapshot()` returns `Ok(None)` when the source has not
//!   declared a position and `Err(OfflineError::Denied)` when it
//!   explicitly refuses — the two are not interchangeable
//!   (`docs/offline-media.md:137-140`, section "Each source owns its
//!   offline decision").
//! - Operational licence is checked both at admission and at offline
//!   rendering; revoked rows are retired but the file is preserved.
//! - Failures are typed (`OfflineError`), redacted (no URL, header value,
//!   body excerpt, or credential), and terminal — a failed row never
//!   becomes playable.
//!
//! These types are deliberately small and exhaustive: the engine module is
//! the only place that orchestrates jobs, the storage module is the only
//! place that touches the filesystem, and the quota module is the only
//! place that decides eviction. The catalog module is the read path that
//! resolves a `MediaKey` to either the live endpoint or the cached file.
//!
//! # Citation convention
//!
//! `doc:<line>` citations refer to `docs/offline-media.md` at
//! `origin/main` `fc5d0d6a` (merge of PR #181) and name the section
//! anchor they fall in.
//!
//! # Persisted-enum encoding
//!
//! Every persisted enum serialises its variant name as kebab-case
//! (`#[serde(rename_all = "kebab-case")]`) and `Display` renders the same
//! kebab-case label, so serde round-trips and redacted log output agree.
//! `EntityValidator` pins the conventional `etag` spelling explicitly
//! (mechanical kebab-case of `ETag` would produce `e-tag`); variants
//! carrying payloads (`EntityValidator`, `OperationalLicence::
//! SourceDeclared`) round-trip the payload and display it separately.
//! Tests `*_serde_and_display` / `*_serde_matches_display` pin every
//! round trip.

use std::fmt;

use serde::{Deserialize, Deserializer, Serialize};

use super::identity::{MediaKey, SourceIncarnationId};

/// Shared 4 KiB ceiling for server-controlled textual metadata captured by
/// the offline contracts (entity-validator payloads, licence labels).
///
/// It deliberately mirrors [`super::identity::MAX_REMOTE_TRACK_ID_BYTES`]:
/// the same untrusted adapter boundary supplies the value, so the same
/// bound defends against a mis-sized or hostile header inflating the
/// persisted row. Enforced by the checked constructors
/// ([`EntityValidator::etag`], [`EntityValidator::last_modified`],
/// [`LicenceLabel::new`]).
pub const MAX_OFFLINE_METADATA_BYTES: usize = super::identity::MAX_REMOTE_TRACK_ID_BYTES;

/// Upper bound for the storage-engine-minted snapshot path. The path is
/// generated by the storage layer and never crosses this layer as a URL or
/// credential, but the contract still bounds the persisted identifier the
/// storage layer mints. Enforced by [`CommittedSnapshot::new`] (the only
/// public constructor of the committed-row contract), which calls
/// [`validate_snapshot_path_bytes`].
pub const MAX_OFFLINE_SNAPSHOT_PATH_BYTES: usize = 4 * 1024;

/// Reject a declared download total above the per-track payload cap.
///
/// At admission, a job whose declared total (`Content-Length` when known)
/// exceeds the per-track payload cap fails
/// [`OfflineError::QuotaExceeded`] *before any network work*
/// (`doc:1264-1266`, section "Global quota and the per-track byte cap").
/// A response whose payload size exactly equals the cap is not a quota
/// failure — it is accepted as end-of-stream (`doc:233-237`,
/// `doc:1592`), and the verify step re-checks the same cap against the
/// verified size before any rename (`doc:498-502`, "Atomic storage"
/// rule 4).
///
/// The declared total is quota input, never a committed size and never a
/// metadata hint with its own byte bound: real audio payloads are
/// megabytes, so any fixed small ceiling on the *hint itself* would
/// reject every real download while the actual protection — the per-track
/// payload cap — lives here instead.
pub const fn check_declared_total(
    declared_total: u64,
    per_track_payload_cap: u64,
) -> Result<(), OfflineError> {
    if declared_total > per_track_payload_cap {
        Err(OfflineError::QuotaExceeded)
    } else {
        Ok(())
    }
}

/// Reject a storage-engine-minted snapshot path whose byte length
/// exceeds [`MAX_OFFLINE_SNAPSHOT_PATH_BYTES`]. The engine never
/// constructs the path; this is the contract the storage layer must
/// honour when minting one. Enforced by [`CommittedSnapshot::new`].
pub const fn validate_snapshot_path_bytes(byte_len: usize) -> Result<(), OfflineError> {
    if byte_len <= MAX_OFFLINE_SNAPSHOT_PATH_BYTES {
        Ok(())
    } else {
        Err(OfflineError::StorageUnavailable)
    }
}

/// A short bounded identifier a source adapter publishes as its licence
/// label (e.g. `subsonic-streaming-self`). It is never a free-form text
/// field, never the full licence text, and never the URL of a licence
/// page: the catalogue carries the licence label for every offline row
/// but never the text (`doc:58`, "Licensing" row; `doc:1151`, the
/// `SourceDeclared` row of the licence table). The application never
/// invents labels — it only carries the ones the adapter publishes.
///
/// The value is an ASCII identifier: non-empty, at most
/// [`MAX_OFFLINE_METADATA_BYTES`] bytes, and every byte an ASCII
/// alphanumeric, `-`, or `_`. Anything else (spaces, punctuation,
/// non-ASCII) is rejected at construction and on deserialisation, so a
/// hostile adapter cannot smuggle prose, markup, or multi-byte sequences
/// into the persisted row.
#[derive(Clone, Eq, PartialEq, Serialize)]
#[serde(transparent)]
pub struct LicenceLabel(String);

impl LicenceLabel {
    /// Validate an adapter-published label: non-empty, at most
    /// [`MAX_OFFLINE_METADATA_BYTES`] bytes, and an ASCII identifier
    /// charset (ASCII alphanumeric, `-`, `_`) — rejecting empty,
    /// over-bound, and out-of-charset values (`None` means discard —
    /// there is no licence state to persist).
    pub fn new(value: impl Into<String>) -> Option<Self> {
        let value = value.into();
        if value.is_empty() || value.len() > MAX_OFFLINE_METADATA_BYTES {
            return None;
        }
        if !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
        {
            return None;
        }
        Some(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for LicenceLabel {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl fmt::Debug for LicenceLabel {
    /// Redacted: the label is non-secret by contract (`doc:1151`) but
    /// bounded-debug keeps adapter-published strings out of logs, same
    /// discipline as `TrackId`.
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("LicenceLabel")
            .field("byte_len", &self.0.len())
            .finish_non_exhaustive()
    }
}

impl<'de> Deserialize<'de> for LicenceLabel {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::new(value)
            .ok_or_else(|| serde::de::Error::custom("licence label empty or over bound"))
    }
}

/// Exact operational licence a source declares for offline replay of its
/// content. Default is `Denied`; a source must explicitly opt in.
///
/// The `SourceDeclared` payload is the bounded [`LicenceLabel`]; only the
/// label — never the licence text — is persisted (`doc:1150-1152`,
/// section "Cached media is licensed only when the source declares it").
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum OperationalLicence {
    /// Default. A cached row may exist structurally but cannot become
    /// playable. Visible to GTK as "Offline unavailable" for that source.
    #[default]
    Denied,
    /// The source declares a contract that allows offline replay of its
    /// content for the user. The label is the only thing persisted.
    SourceDeclared(LicenceLabel),
    /// The source or backend has changed the licence after a row was
    /// committed. Visible as "Licence revoked"; the row is retired but
    /// the file is preserved.
    Revoked,
}

impl fmt::Display for OperationalLicence {
    /// The kebab-case variant label, except that `SourceDeclared` renders
    /// the carried licence label — the persisted state is the label
    /// itself (`doc:190`, "Committed snapshots play without a live
    /// authority").
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Denied => formatter.write_str("denied"),
            Self::SourceDeclared(label) => formatter.write_str(label.as_str()),
            Self::Revoked => formatter.write_str("revoked"),
        }
    }
}

/// The byte-cap holder a backend returns inside an admitted offline
/// capability. The cap is a per-source upper bound on the total bytes
/// the cache will commit for that source; the global quota layer still
/// bounds every committed row, so this cap is advisory at admission
/// time and authoritative only within the source.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OfflineSnapshot {
    /// Per-source byte total bounded at the source-adapter-declared cap.
    pub source_byte_cap: u64,
}

impl OfflineSnapshot {
    /// Construct a snapshot capability with the supplied byte cap. The
    /// cap is a source-adapter-declared upper bound; the engine still
    /// caps every committed row by the global quota.
    pub fn new(source_byte_cap: u64) -> Self {
        Self { source_byte_cap }
    }
}

/// State of one admitted download job. `Queued` through `Committed` are
/// transient or terminal-success; `Failed` and `Cancelled` are
/// terminal-failure states. The transitions are strictly monotonic — a
/// job never re-enters `Queued` from a later state.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum JobState {
    #[default]
    Queued,
    Connecting,
    Receiving,
    Verifying,
    Committing,
    Committed,
    Failed,
    Cancelled,
}

impl JobState {
    /// Whether this state is terminal. A terminal state never advances
    /// again; the engine records it and releases the lease.
    pub fn is_terminal(self) -> bool {
        matches!(self, Self::Committed | Self::Failed | Self::Cancelled)
    }
}

impl fmt::Display for JobState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Queued => "queued",
            Self::Connecting => "connecting",
            Self::Receiving => "receiving",
            Self::Verifying => "verifying",
            Self::Committing => "committing",
            Self::Committed => "committed",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
        };
        formatter.write_str(label)
    }
}

/// Structured, terminal cause of a failed download.
///
/// Every variant is a fixed category. The variant name, and the variant
/// name only, is what the cache rows, GTK, the journal logs, and the
/// redacted failure messages ever expose. No raw HTTP status, redirect
/// path, body excerpt, header value, URL parameter, or credential
/// appears in the failure (`doc:276-287`, "Failure is structured",
/// rule 4). An `OfflineError` appears in the contract only as the
/// terminal `failure` field of a job row (`doc:211`).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum OfflineError {
    /// Network failure after the job's bounded resume budget is spent;
    /// recorded as the terminal cause (`doc:211`, "Failure is
    /// structured"). Retries happen inside the job's budget while the
    /// job is still live — once this variant is recorded the job is
    /// terminal.
    Network,
    /// The source's credential expired or was revoked mid-download.
    /// The lease is revoked; the cache row is not promoted. The user
    /// reauthenticates through the source's normal path.
    AuthExpired,
    /// The lease was revoked by the source lifecycle before commit.
    LeaseRevoked,
    /// Capability-level refusal surfaced by `offline_snapshot` for a
    /// source that explicitly opts out (`doc:139-140`, "Each source owns
    /// its offline decision"; `doc:283-286`). Distinct from `Ok(None)`
    /// (capability not declared) and from [`OfflineError::LicenceDenied`]
    /// (the operational-licence verdict). Radio-Browser is the reviewed
    /// hard-deny (`doc:153-156`, `doc:1085`).
    Denied,
    /// The post-write SHA-256 of the bytes on disk did not match the
    /// server-advertised digest. Terminal; the temp file is unlinked.
    IntegrityMismatch,
    /// No digest provenance tier could supply an expected digest: the
    /// backend advertises none and double-fetch verification could not
    /// produce one. Terminal before publish; the temp file is unlinked
    /// and nothing was renamed (`doc:1109-1112`, "Digest provenance
    /// tiers"; `doc:1588`).
    IntegrityUnverifiable,
    /// The source declared `OperationalLicence::Denied` or `Revoked` at
    /// admission. The job is refused before any network work
    /// (`doc:1590`).
    LicenceDenied,
    /// The global quota or the per-track payload cap was exceeded before
    /// commit. The temp file is unlinked; no cache row is created
    /// (`doc:1264-1266`, `doc:498-502`).
    QuotaExceeded,
    /// Defined safe refusal when a job has spent its bounded
    /// publish-attempt budget on repeated crashes in the rename window;
    /// it is not a quota failure and never stands for an uncharged write
    /// (`doc:280-283`, "Failure is structured"; exhaustion verdict
    /// `doc:1593`).
    PublishRetriesExhausted,
    /// The filesystem refused the temp reservation or the rename
    /// (`doc:650-661`, "Atomic storage" phase table; `doc:1595`).
    StorageUnavailable,
    /// Retained per the contract's redacted-variant list (`doc:280-281`).
    /// The capability refusal itself is [`OfflineError::Denied`]; this
    /// variant stays pending tr-92a's answer on whether any
    /// adapter-specific refusal still needs a dedicated variant.
    UnsupportedSource,
}

impl fmt::Display for OfflineError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Network => "network",
            Self::AuthExpired => "auth-expired",
            Self::LeaseRevoked => "lease-revoked",
            Self::Denied => "denied",
            Self::IntegrityMismatch => "integrity-mismatch",
            Self::IntegrityUnverifiable => "integrity-unverifiable",
            Self::LicenceDenied => "licence-denied",
            Self::QuotaExceeded => "quota-exceeded",
            Self::PublishRetriesExhausted => "publish-retries-exhausted",
            Self::StorageUnavailable => "storage-unavailable",
            Self::UnsupportedSource => "unsupported-source",
        };
        formatter.write_str(label)
    }
}

/// Bounded server-controlled payload carried by an [`EntityValidator`]
/// (`ETag` / `Last-Modified` value). The inner string is private:
/// every construction path goes through [`ValidatorPayload::new`], so
/// no validator value outside [`MAX_OFFLINE_METADATA_BYTES`] can exist
/// in the type system — the same discipline as [`LicenceLabel`].
#[derive(Clone, Eq, PartialEq, Serialize)]
#[serde(transparent)]
pub struct ValidatorPayload(String);

impl ValidatorPayload {
    /// Validate a captured server value against
    /// [`MAX_OFFLINE_METADATA_BYTES`], rejecting empty and over-bound
    /// values (`None` means discard — the job falls back to the
    /// no-validator restart-only rule, `doc:205`).
    pub fn new(value: impl Into<String>) -> Option<Self> {
        bounded_validator(value.into()).map(Self)
    }

    /// The bounded server-controlled payload, for the engine's `If-Range`
    /// request construction only. Never logged, never exposed through GTK.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for ValidatorPayload {
    /// Redacted: byte length only; the server-controlled value never
    /// reaches logs (`offline.rs` redaction contract, `doc:276-287`).
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ValidatorPayload")
            .field("byte_len", &self.0.len())
            .finish_non_exhaustive()
    }
}

impl<'de> Deserialize<'de> for ValidatorPayload {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::new(value).ok_or_else(|| de_error("entity validator"))
    }
}

/// Entity validator captured from the first successful response of a
/// download job (`doc:205`, job-model table). A strong `ETag` is
/// preferred; `Last-Modified` is the fallback when no strong entity tag
/// exists. `Some(validator)` is required for any resumption — the
/// engine re-requests the remainder with `Range` **and** `If-Range`
/// carrying the captured value; `None` disables resume and restricts
/// the job to a full restart (`doc:237-242`, resumption rule).
///
/// The payload is a server-controlled string, so it is bounded by
/// construction: variants carry the private-field [`ValidatorPayload`]
/// (bounded at [`MAX_OFFLINE_METADATA_BYTES`], sharing the
/// `MAX_REMOTE_TRACK_ID_BYTES` rationale), deserialisation goes through
/// the checked constructors, and `Debug` renders the kind plus byte
/// length only.
#[derive(Clone, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum EntityValidator {
    /// Strong entity tag captured from the first successful response.
    /// The persisted label is the conventional `etag` (mechanical
    /// kebab-case of `ETag` would be `e-tag`); `Display` matches.
    #[serde(rename = "etag")]
    ETag(ValidatorPayload),
    /// `Last-Modified` timestamp captured when no strong ETag exists.
    LastModified(ValidatorPayload),
}

impl EntityValidator {
    /// Capture a strong `ETag`, rejecting empty and over-bound payloads.
    /// `None` means discard: the job falls back to the no-validator
    /// restart-only rule (`doc:205`).
    pub fn etag(value: impl Into<String>) -> Option<Self> {
        Some(Self::ETag(ValidatorPayload::new(value)?))
    }

    /// Capture a `Last-Modified` timestamp, rejecting empty and
    /// over-bound payloads. `None` means discard: the job falls back to
    /// the no-validator restart-only rule (`doc:205`).
    pub fn last_modified(value: impl Into<String>) -> Option<Self> {
        Some(Self::LastModified(ValidatorPayload::new(value)?))
    }

    /// Whether this validator is a strong entity tag. A strong `ETag`
    /// (preferred) authorises resumption; `Last-Modified` is the
    /// fallback (`doc:205`).
    pub fn is_strong(&self) -> bool {
        matches!(self, Self::ETag(_))
    }

    /// The redacted kind label — `etag` or `last-modified`.
    pub fn kind(&self) -> &'static str {
        match self {
            Self::ETag(_) => "etag",
            Self::LastModified(_) => "last-modified",
        }
    }

    /// The bounded server-controlled payload, for the engine's `If-Range`
    /// request construction only. Never logged, never exposed through GTK.
    pub fn value(&self) -> &str {
        match self {
            Self::ETag(payload) | Self::LastModified(payload) => payload.as_str(),
        }
    }

    fn payload_len(&self) -> usize {
        self.value().len()
    }
}

fn bounded_validator(value: String) -> Option<String> {
    if value.is_empty() || value.len() > MAX_OFFLINE_METADATA_BYTES {
        return None;
    }
    Some(value)
}

impl fmt::Display for EntityValidator {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.kind())
    }
}

impl fmt::Debug for EntityValidator {
    /// Redacted: kind plus byte length; the server-controlled payload
    /// never reaches logs.
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("EntityValidator")
            .field("kind", &self.kind())
            .field("byte_len", &self.payload_len())
            .finish_non_exhaustive()
    }
}

impl<'de> Deserialize<'de> for EntityValidator {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        #[serde(rename_all = "kebab-case")]
        enum RawValidator {
            #[serde(rename = "etag")]
            ETag(String),
            LastModified(String),
        }

        match RawValidator::deserialize(deserializer)? {
            RawValidator::ETag(value) => {
                Self::etag(value).ok_or_else(|| de_error("entity validator"))
            }
            RawValidator::LastModified(value) => {
                Self::last_modified(value).ok_or_else(|| de_error("entity validator"))
            }
        }
    }
}

fn de_error<E: serde::de::Error>(what: &str) -> E {
    E::custom(format!("{what} payload empty or over bound"))
}

/// Which provenance tier supplied the expected digest a committed
/// snapshot was verified against (`doc:1094-1112`, "Digest provenance
/// tiers"). An expected digest may come from exactly these two places; a
/// backend with neither tier cannot be downloaded from and fails
/// [`OfflineError::IntegrityUnverifiable`] before any byte is promoted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum DigestProvenance {
    /// A digest whose field, header, or API property is named in the
    /// contract's capability matrix and documented in the adapter. It
    /// is compared exactly against the engine-computed SHA-256.
    Advertised,
    /// No digest is advertised: the engine issued a fresh authenticated
    /// second transfer for the same resource and required the SHA-256
    /// of both transfers to be identical. The offline quota is charged
    /// once, for the committed bytes.
    DoubleFetch,
}

impl fmt::Display for DigestProvenance {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Advertised => "advertised",
            Self::DoubleFetch => "double-fetch",
        };
        formatter.write_str(label)
    }
}

/// The identity triple of one offline job or committed row
/// (`doc:199-211`, job-model table; `doc:289-294`, "One job per
/// `(media_key, source_incarnation)`", rule 5). Grouped because the
/// contract treats the triple as one identity: restart authorization
/// compares the durable `(media_key, source_incarnation)` pair and
/// never the epoch, while `capability_epoch` only orders supersession
/// within one process run (`doc:325-342`).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SnapshotIdentity {
    /// The live `(SourceId, TrackId)` media identity.
    pub media_key: MediaKey,
    /// Durable, non-secret identity of the owning source incarnation
    /// (`doc:202`). Never a transient generation number.
    pub source_incarnation: SourceIncarnationId,
    /// The source registry's accepted generation, process-local
    /// ordering only (`doc:203`); never restart-stable (`doc:326-327`).
    pub capability_epoch: u64,
}

impl SnapshotIdentity {
    /// Assemble the identity triple of one job or committed row.
    pub const fn new(
        media_key: MediaKey,
        source_incarnation: SourceIncarnationId,
        capability_epoch: u64,
    ) -> Self {
        Self {
            media_key,
            source_incarnation,
            capability_epoch,
        }
    }
}

/// One immutable result of one admitted download job at one version.
///
/// Refresh does not mutate; it siblings. A new snapshot for the same
/// `media_key` is a new row; the predecessor is queued for unlink
/// once the new snapshot is committed and integrity-checked.
///
/// Fields are private by design: the checked [`CommittedSnapshot::new`]
/// is the boundary that enforces the snapshot-path bound and the fixed
/// `[u8; 32]` digest shape, so every "Enforced by" claim about the
/// persisted row has a real call site.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommittedSnapshot {
    /// The identity triple this snapshot was admitted under
    /// ([`SnapshotIdentity`]).
    identity: SnapshotIdentity,
    /// Total committed byte count. Equal to the post-write `current_bytes`
    /// when the job reached `Committed`.
    byte_size: u64,
    /// SHA-256 of the bytes on disk, computed post-write and re-checked
    /// on resume. Fixed 32-byte digest — hex rendering is derived, never
    /// stored.
    sha256: [u8; 32],
    /// Which provenance tier supplied the expected digest this snapshot
    /// was verified against (`doc:1094-1112`).
    digest_provenance: DigestProvenance,
    /// The storage-engine-minted path inside the cache root. Opaque; no
    /// URL, credential, or credential-bearing parameter appears here.
    /// Bounded by [`MAX_OFFLINE_SNAPSHOT_PATH_BYTES`].
    cache_path: String,
    /// The licence state recorded at commit; for a declared licence this
    /// carries the persisted label only (`doc:190`, `doc:1150-1152`).
    licence: OperationalLicence,
    /// The committed-at epoch in seconds.
    committed_at_epoch_secs: u64,
}

impl CommittedSnapshot {
    /// Checked constructor for a committed row.
    ///
    /// Enforces the snapshot-path bound
    /// ([`MAX_OFFLINE_SNAPSHOT_PATH_BYTES`], via
    /// [`validate_snapshot_path_bytes`]) and takes the digest in its
    /// canonical `[u8; 32]` shape, so a committed row cannot exist with
    /// an unbounded path or a non-digest value.
    pub fn new(
        identity: SnapshotIdentity,
        byte_size: u64,
        sha256: [u8; 32],
        digest_provenance: DigestProvenance,
        cache_path: String,
        licence: OperationalLicence,
        committed_at_epoch_secs: u64,
    ) -> Result<Self, OfflineError> {
        validate_snapshot_path_bytes(cache_path.len())?;
        Ok(Self {
            identity,
            byte_size,
            sha256,
            digest_provenance,
            cache_path,
            licence,
            committed_at_epoch_secs,
        })
    }

    /// The identity triple this snapshot was admitted under.
    pub fn identity(&self) -> &SnapshotIdentity {
        &self.identity
    }

    pub fn media_key(&self) -> &MediaKey {
        &self.identity.media_key
    }

    pub fn source_incarnation(&self) -> SourceIncarnationId {
        self.identity.source_incarnation
    }

    pub fn capability_epoch(&self) -> u64 {
        self.identity.capability_epoch
    }

    pub fn byte_size(&self) -> u64 {
        self.byte_size
    }

    pub fn sha256(&self) -> &[u8; 32] {
        &self.sha256
    }

    /// Lowercase hex rendering of the committed digest.
    pub fn sha256_hex(&self) -> String {
        const HEX: &[u8; 16] = b"0123456789abcdef";
        let mut encoded = String::with_capacity(self.sha256.len() * 2);
        for &byte in &self.sha256 {
            encoded.push(char::from(HEX[usize::from(byte >> 4)]));
            encoded.push(char::from(HEX[usize::from(byte & 0x0f)]));
        }
        encoded
    }

    pub fn digest_provenance(&self) -> DigestProvenance {
        self.digest_provenance
    }

    pub fn cache_path(&self) -> &str {
        &self.cache_path
    }

    pub fn licence(&self) -> &OperationalLicence {
        &self.licence
    }

    pub fn committed_at_epoch_secs(&self) -> u64 {
        self.committed_at_epoch_secs
    }
}

/// A live, in-flight download job. The engine owns one `JobRecord` per
/// `(media_key, source_incarnation)` and never admits a second while the
/// first is non-terminal (`doc:289-294`, "One job per
/// `(media_key, source_incarnation)`", rule 5).
///
/// Restart authorization compares the durable
/// `(SourceId, SourceIncarnationId)` pair — never a transient generation
/// number; `capability_epoch` only orders supersession within one
/// process run, and numeric equality is never authorization
/// (`doc:325-342`, "Authenticated, resumable download jobs").
///
/// The field set and types mirror the contract's job-model table at
/// `doc:199-211`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct JobRecord {
    pub media_key: MediaKey,
    /// Durable, non-secret identity of the owning source incarnation,
    /// recorded at admission (`doc:202`). Restart authorization compares
    /// this durable identity, never a transient generation number.
    pub source_incarnation: SourceIncarnationId,
    /// The source registry's accepted generation, process-local ordering
    /// only (`doc:203`); never restart-stable (`doc:326-327`).
    pub capability_epoch: u64,
    /// Server-advertised `Content-Length` when the response declares one;
    /// quota input only, never a committed size and never authoritative
    /// (`doc:204`). An over-cap declared total fails
    /// [`check_declared_total`] at admission.
    pub requested_bytes: Option<u64>,
    /// Entity validator captured from the first successful response.
    /// `Some` is required for any resumption; `None` disables resume
    /// and restricts the job to a full restart (`doc:205`).
    pub resume_validator: Option<EntityValidator>,
    pub current_bytes: u64,
    /// Progressively trusted only after the full file is received and
    /// re-checked post-write. `None` until the engine reaches `Verifying`;
    /// `Some(digest)` once a candidate digest has been computed and
    /// compared against the expected value.
    pub current_sha256: Option<[u8; 32]>,
    /// Durable bytes the job's journal and sidecar records occupy;
    /// engine-owned, charged against the same global quota as payload
    /// (`doc:208`, job-model table).
    pub journal_bytes: u64,
    pub state: JobState,
    /// Opaque lease reference of the in-flight HTTP request. Owned by the
    /// source registry; the engine treats it as identity and never inspects
    /// its payload.
    pub last_lease: Option<LeaseId>,
    /// Redacted, structured, terminal cause when `state = Failed`
    /// (`doc:211`).
    pub failure: Option<OfflineError>,
}

impl JobRecord {
    pub fn new(
        media_key: MediaKey,
        source_incarnation: SourceIncarnationId,
        capability_epoch: u64,
    ) -> Self {
        Self {
            media_key,
            source_incarnation,
            capability_epoch,
            requested_bytes: None,
            resume_validator: None,
            current_bytes: 0,
            current_sha256: None,
            journal_bytes: 0,
            state: JobState::Queued,
            last_lease: None,
            failure: None,
        }
    }
}

/// Opaque identifier of one accepted revocable lease. The engine treats
/// it as identity and never inspects its payload; the source registry is
/// the only authority that can mint, validate, or revoke a value.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct LeaseId(u64);

impl LeaseId {
    /// Adopt an already-minted lease identifier. Only the source registry
    /// calls this; the engine never invents a lease from raw integers.
    pub const fn from_raw(raw: u64) -> Self {
        Self(raw)
    }

    /// Internal accessor used by tests and by the source registry's
    /// adapter boundary. Never exposed through GTK, the catalogue reader,
    /// or the persisted cache row.
    pub const fn raw(self) -> u64 {
        self.0
    }
}

/// Resolve the offline catalogue read for one `(SourceId, TrackId)`
/// pair. The catalogue is read-only and never mints `SourceId` or
/// `TrackId` values; it only answers whether a committed snapshot is
/// available, returns its immutable record, or returns `None` to mean
/// "the live endpoint is the source of truth".
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OfflineCatalogueEntry {
    /// No cached snapshot is available; live playback is the source of
    /// truth.
    LiveOnly,
    /// A committed snapshot exists and is playable.
    Cached(CommittedSnapshot),
    /// A committed snapshot exists but its licence has been revoked.
    /// The file is preserved on disk; the row is not playable.
    Revoked(CommittedSnapshot),
}

#[cfg(test)]
mod tests;
