//! Bounded download/cache contracts for offline media.
//!
//! These types implement the source-scoped offline media contract
//! documented in `docs/offline-media.md` (P3.1). The contract requires:
//!
//! - The download/cache engine never becomes a source of its own. Cached
//!   items are owned by an existing `Source` and identified by the same
//!   `(SourceId, TrackId)` pair used by live playback.
//! - Offline capability is default-deny and source-scoped:
//!   `offline_snapshot()` returns `Ok(None)` when the source has not
//!   declared a position and `Err(OfflineError::Denied)` when it
//!   explicitly refuses — the two are not interchangeable
//!   (`docs/offline-media.md:137-140`, section "Each source owns its
//!   offline decision").
//! - Operational licence is checked both at admission and at offline
//!   rendering; revoked rows are retired but the file is preserved.
//! - Failures are typed (`OfflineError`), redacted (no URL, header value,
//!   body excerpt, or credential), and terminal — a failed row never
//!   becomes playable.
//!
//! These types are deliberately small and exhaustive: the engine module is
//! the only place that orchestrates jobs, the storage module is the only
//! place that touches the filesystem, and the quota module is the only
//! place that decides eviction. The catalog module is the read path that
//! resolves a `MediaKey` to either the live endpoint or the cached file.
//!
//! # Citation convention
//!
//! `doc:<line>` citations refer to `docs/offline-media.md` at
//! `origin/main` `fc5d0d6a` (merge of PR #181) and name the section
//! anchor they fall in.
//!
//! # Persisted-enum encoding
//!
//! Every persisted enum serialises its variant name as kebab-case
//! (`#[serde(rename_all = "kebab-case")]`) and `Display` renders the same
//! kebab-case label, so serde round-trips and redacted log output agree.
//! `EntityValidator` pins the conventional `etag` spelling explicitly
//! (mechanical kebab-case of `ETag` would produce `e-tag`); variants
//! carrying payloads (`EntityValidator`, `OperationalLicence::
//! SourceDeclared`) round-trip the payload and display it separately.
//! Tests `*_serde_and_display` / `*_serde_matches_display` pin every
//! round trip.

use std::fmt;

use serde::{Deserialize, Deserializer, Serialize};

use super::identity::{MediaKey, SourceIncarnationId};

/// Shared 4 KiB ceiling for server-controlled textual metadata captured by
/// the offline contracts (entity-validator payloads, licence labels).
///
/// It deliberately mirrors [`super::identity::MAX_REMOTE_TRACK_ID_BYTES`]:
/// the same untrusted adapter boundary supplies the value, so the same
/// bound defends against a mis-sized or hostile header inflating the
/// persisted row. Enforced by the checked constructors
/// ([`EntityValidator::etag`], [`EntityValidator::last_modified`],
/// [`LicenceLabel::new`]).
pub const MAX_OFFLINE_METADATA_BYTES: usize = super::identity::MAX_REMOTE_TRACK_ID_BYTES;

/// Upper bound for the storage-engine-minted snapshot path. The path is
/// generated by the storage layer and never crosses this layer as a URL or
/// credential, but the contract still bounds the persisted identifier the
/// storage layer mints. Enforced by [`CommittedSnapshot::new`] (the only
/// public constructor of the committed-row contract), which calls
/// [`validate_snapshot_path_bytes`].
pub const MAX_OFFLINE_SNAPSHOT_PATH_BYTES: usize = 4 * 1024;

/// Reject a declared download total above the per-track payload cap.
///
/// At admission, a job whose declared total (`Content-Length` when known)
/// that exceeds the per-track payload cap fails
/// [`OfflineError::QuotaExceeded`] *before any network work*
/// (`doc:1264-1266`, section "Global quota and the per-track byte cap").
/// A response whose payload size exactly equals the cap is not a quota
/// failure — it is accepted as end-of-stream (`doc:233-237`,
/// `doc:1592`), and the verify step re-checks the same cap against the
/// verified size before any rename (`doc:498-502`, "Atomic storage"
/// rule 4).
///
/// The declared total is quota input, never a committed size and never a
/// metadata hint with its own byte bound: real audio payloads are
/// megabytes, so any fixed small ceiling on the *hint itself* would
/// reject every real download while the actual protection — the per-track
/// payload cap — lives here instead.
pub const fn check_declared_total(
    declared_total: u64,
    per_track_payload_cap: u64,
) -> Result<(), OfflineError> {
    if declared_total > per_track_payload_cap {
        Err(OfflineError::QuotaExceeded)
    } else {
        Ok(())
    }
}

/// Reject a storage-engine-minted snapshot path whose byte length
/// exceeds [`MAX_OFFLINE_SNAPSHOT_PATH_BYTES`]. The engine never
/// constructs the path; this is the contract the storage layer must
/// honour when minting one. Enforced by [`CommittedSnapshot::new`].
pub const fn validate_snapshot_path_bytes(byte_len: usize) -> Result<(), OfflineError> {
    if byte_len <= MAX_OFFLINE_SNAPSHOT_PATH_BYTES {
        Ok(())
    } else {
        Err(OfflineError::StorageUnavailable)
    }
}

/// A short bounded identifier a source adapter publishes as its licence
/// label (e.g. `subsonic-streaming-self`). It is never a free-form text
/// field, never the full licence text, and never the URL of a licence
/// page: the catalogue carries the licence label for every offline row
/// but never the text (`doc:53`, "Licensing" row; `doc:1151`, the
/// `SourceDeclared` row of the licence table). The application never
/// invents labels — it only carries the ones the adapter publishes.
#[derive(Clone, Eq, PartialEq, Serialize)]
#[serde(transparent)]
pub struct LicenceLabel(String);

impl LicenceLabel {
    /// Validate an adapter-published label against
    /// [`MAX_OFFLINE_METADATA_BYTES`], rejecting empty and over-bound
    /// values (`None` means discard — there is no licence state to
    /// persist).
    pub fn new(value: impl Into<String>) -> Option<Self> {
        let value = value.into();
        if value.is_empty() || value.len() > MAX_OFFLINE_METADATA_BYTES {
            return None;
        }
        Some(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for LicenceLabel {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl fmt::Debug for LicenceLabel {
    /// Redacted: the label is non-secret by contract (`doc:1151`) but
    /// bounded-debug keeps adapter-published strings out of logs, same
    /// discipline as `TrackId`.
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("LicenceLabel")
            .field("byte_len", &self.0.len())
            .finish_non_exhaustive()
    }
}

impl<'de> Deserialize<'de> for LicenceLabel {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::new(value)
            .ok_or_else(|| serde::de::Error::custom("licence label empty or over bound"))
    }
}

/// Exact operational licence a source declares for offline replay of its
/// content. Default is `Denied`; a source must explicitly opt in.
///
/// The `SourceDeclared` payload is the bounded [`LicenceLabel`]; only the
/// label — never the licence text — is persisted (`doc:1150-1152`,
/// section "Cached media is licensed only when the source declares it").
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum OperationalLicence {
    /// Default. A cached row may exist structurally but cannot become
    /// playable. Visible to GTK as "Offline unavailable" for that source.
    #[default]
    Denied,
    /// The source declares a contract that allows offline replay of its
    /// content for the user. The label is the only thing persisted.
    SourceDeclared(LicenceLabel),
    /// The source or backend has changed the licence after a row was
    /// committed. Visible as "Licence revoked"; the row is retired but
    /// the file is preserved.
    Revoked,
}

impl fmt::Display for OperationalLicence {
    /// The kebab-case variant label, except that `SourceDeclared` renders
    /// the carried licence label — the persisted state is the label
    /// itself (`doc:190`, "Committed snapshots play without a live
    /// authority").
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Denied => formatter.write_str("denied"),
            Self::SourceDeclared(label) => formatter.write_str(label.as_str()),
            Self::Revoked => formatter.write_str("revoked"),
        }
    }
}

/// The byte-cap holder a backend returns inside an admitted offline
/// capability. The cap is a per-source upper bound on the total bytes
/// the cache will commit for that source; the global quota layer still
/// bounds every committed row, so this cap is advisory at admission
/// time and authoritative only within the source.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OfflineSnapshot {
    /// Per-source byte total bounded at the source-adapter-declared cap.
    pub source_byte_cap: u64,
}

impl OfflineSnapshot {
    /// Construct a snapshot capability with the supplied byte cap. The
    /// cap is a source-adapter-declared upper bound; the engine still
    /// caps every committed row by the global quota.
    pub fn new(source_byte_cap: u64) -> Self {
        Self { source_byte_cap }
    }
}

/// State of one admitted download job. `Queued` through `Committed` are
/// transient or terminal-success; `Failed` and `Cancelled` are
/// terminal-failure states. The transitions are strictly monotonic — a
/// job never re-enters `Queued` from a later state.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum JobState {
    #[default]
    Queued,
    Connecting,
    Receiving,
    Verifying,
    Committing,
    Committed,
    Failed,
    Cancelled,
}

impl JobState {
    /// Whether this state is terminal. A terminal state never advances
    /// again; the engine records it and releases the lease.
    pub fn is_terminal(self) -> bool {
        matches!(self, Self::Committed | Self::Failed | Self::Cancelled)
    }
}

impl fmt::Display for JobState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Queued => "queued",
            Self::Connecting => "connecting",
            Self::Receiving => "receiving",
            Self::Verifying => "verifying",
            Self::Committing => "committing",
            Self::Committed => "committed",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
        };
        formatter.write_str(label)
    }
}

/// Structured, terminal cause of a failed download.
///
/// Every variant is a fixed category. The variant name, and the variant
/// name only, is what the cache rows, GTK, the journal logs, and the
/// redacted failure messages ever expose. No raw HTTP status, redirect
/// path, body excerpt, header value, URL parameter, or credential
/// appears in the failure (`doc:276-287`, "Failure is structured",
/// rule 4). An `OfflineError` appears in the contract only as the
/// terminal `failure` field of a job row (`doc:211`).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum OfflineError {
    /// Network failure after the job's bounded resume budget is spent;
    /// recorded as the terminal cause (`doc:211`, "Failure is
    /// structured"). Retries happen inside the job's budget while the
    /// job is still live — once this variant is recorded the job is
    /// terminal.
    Network,
    /// The source's credential expired or was revoked mid-download.
    /// The lease is revoked; the cache row is not promoted. The user
    /// reauthenticates through the source's normal path.
    AuthExpired,
    /// The lease was revoked by the source lifecycle before commit.
    LeaseRevoked,
    /// Capability-level refusal surfaced by `offline_snapshot` for a
    /// source that explicitly opts out (`doc:139-140`, "Each source owns
    /// its offline decision"; `doc:283-286`). Distinct from `Ok(None)`
    /// (capability not declared) and from [`OfflineError::LicenceDenied`]
    /// (the operational-licence verdict). Radio-Browser is the reviewed
    /// hard-deny (`doc:153-156`, `doc:1085`).
    Denied,
    /// The post-write SHA-256 of the bytes on disk did not match the
    /// server-advertised digest. Terminal; the temp file is unlinked.
    IntegrityMismatch,
    /// No digest provenance tier could supply an expected digest: the
    /// backend advertises none and double-fetch verification could not
    /// produce one. Terminal before publish; the temp file is unlinked
    /// and nothing was renamed (`doc:1109-1112`, "Digest provenance
    /// tiers"; `doc:1588`).
    IntegrityUnverifiable,
    /// The source declared `OperationalLicence::Denied` or `Revoked` at
    /// admission. The job is refused before any network work
    /// (`doc:1590`).
    LicenceDenied,
    /// The global quota or the per-track payload cap was exceeded before
    /// commit. The temp file is unlinked; no cache row is created
    /// (`doc:1264-1266`, `doc:498-502`).
    QuotaExceeded,
    /// Defined safe refusal when a job has spent its bounded
    /// publish-attempt budget on repeated crashes in the rename window;
    /// it is not a quota failure and never stands for an uncharged write
    /// (`doc:280-283`, "Failure is structured"; exhaustion verdict
    /// `doc:1593`).
    PublishRetriesExhausted,
    /// The filesystem refused the temp reservation or the rename
    /// (`doc:650-661`, "Atomic storage" phase table; `doc:1595`).
    StorageUnavailable,
    /// Retained per the contract's redacted-variant list (`doc:280-281`).
    /// The capability refusal itself is [`OfflineError::Denied`]; this
    /// variant stays pending tr-92a's answer on whether any
    /// adapter-specific refusal still needs a dedicated variant.
    UnsupportedSource,
}

impl fmt::Display for OfflineError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Network => "network",
            Self::AuthExpired => "auth-expired",
            Self::LeaseRevoked => "lease-revoked",
            Self::Denied => "denied",
            Self::IntegrityMismatch => "integrity-mismatch",
            Self::IntegrityUnverifiable => "integrity-unverifiable",
            Self::LicenceDenied => "licence-denied",
            Self::QuotaExceeded => "quota-exceeded",
            Self::PublishRetriesExhausted => "publish-retries-exhausted",
            Self::StorageUnavailable => "storage-unavailable",
            Self::UnsupportedSource => "unsupported-source",
        };
        formatter.write_str(label)
    }
}

/// Entity validator captured from the first successful response of a
/// download job (`doc:205`, job-model table). A strong `ETag` is
/// preferred; `Last-Modified` is the fallback when no strong entity tag
/// exists. `Some(validator)` is required for any resumption — the
/// engine re-requests the remainder with `Range` **and** `If-Range`
/// carrying the captured value; `None` disables resume and restricts
/// the job to a full restart (`doc:237-242`, resumption rule).
///
/// The payload is a server-controlled string, so it is private and
/// bounded: the checked constructors reject empty and over-bound values
/// against [`MAX_OFFLINE_METADATA_BYTES`] (sharing the
/// `MAX_REMOTE_TRACK_ID_BYTES` rationale), deserialisation goes through
/// the constructors, and `Debug` renders the kind plus byte length only.
#[derive(Clone, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum EntityValidator {
    /// Strong entity tag captured from the first successful response.
    /// The persisted label is the conventional `etag` (mechanical
    /// kebab-case of `ETag` would be `e-tag`); `Display` matches.
    #[serde(rename = "etag")]
    ETag(String),
    /// `Last-Modified` timestamp captured when no strong ETag exists.
    LastModified(String),
}

impl EntityValidator {
    /// Capture a strong `ETag`, rejecting empty and over-bound payloads.
    /// `None` means discard: the job falls back to the no-validator
    /// restart-only rule (`doc:205`).
    pub fn etag(value: impl Into<String>) -> Option<Self> {
        bounded_validator(value.into()).map(Self::ETag)
    }

    /// Capture a `Last-Modified` timestamp, rejecting empty and
    /// over-bound payloads. `None` means discard: the job falls back to
    /// the no-validator restart-only rule (`doc:205`).
    pub fn last_modified(value: impl Into<String>) -> Option<Self> {
        bounded_validator(value.into()).map(Self::LastModified)
    }

    /// Whether this validator is a strong entity tag. A strong `ETag`
    /// (preferred) authorises resumption; `Last-Modified` is the
    /// fallback (`doc:205`).
    pub fn is_strong(&self) -> bool {
        matches!(self, Self::ETag(_))
    }

    /// The redacted kind label — `etag` or `last-modified`.
    pub fn kind(&self) -> &'static str {
        match self {
            Self::ETag(_) => "etag",
            Self::LastModified(_) => "last-modified",
        }
    }

    /// The bounded server-controlled payload, for the engine's `If-Range`
    /// request construction only. Never logged, never exposed through GTK.
    pub fn value(&self) -> &str {
        match self {
            Self::ETag(value) | Self::LastModified(value) => value,
        }
    }

    fn payload_len(&self) -> usize {
        self.value().len()
    }
}

fn bounded_validator(value: String) -> Option<String> {
    if value.is_empty() || value.len() > MAX_OFFLINE_METADATA_BYTES {
        return None;
    }
    Some(value)
}

impl fmt::Display for EntityValidator {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.kind())
    }
}

impl fmt::Debug for EntityValidator {
    /// Redacted: kind plus byte length; the server-controlled payload
    /// never reaches logs.
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("EntityValidator")
            .field("kind", &self.kind())
            .field("byte_len", &self.payload_len())
            .finish_non_exhaustive()
    }
}

impl<'de> Deserialize<'de> for EntityValidator {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        #[serde(rename_all = "kebab-case")]
        enum RawValidator {
            #[serde(rename = "etag")]
            ETag(String),
            LastModified(String),
        }

        match RawValidator::deserialize(deserializer)? {
            RawValidator::ETag(value) => {
                Self::etag(value).ok_or_else(|| de_error("entity validator"))
            }
            RawValidator::LastModified(value) => {
                Self::last_modified(value).ok_or_else(|| de_error("entity validator"))
            }
        }
    }
}

fn de_error<E: serde::de::Error>(what: &str) -> E {
    E::custom(format!("{what} payload empty or over bound"))
}

/// Which provenance tier supplied the expected digest a committed
/// snapshot was verified against (`doc:1094-1112`, "Digest provenance
/// tiers"). An expected digest may come from exactly these two places; a
/// backend with neither tier cannot be downloaded from and fails
/// [`OfflineError::IntegrityUnverifiable`] before any byte is promoted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum DigestProvenance {
    /// A digest whose field, header, or API property is named in the
    /// contract's capability matrix and documented in the adapter. It
    /// is compared exactly against the engine-computed SHA-256.
    Advertised,
    /// No digest is advertised: the engine issued a fresh authenticated
    /// second transfer for the same resource and required the SHA-256
    /// of both transfers to be identical. The offline quota is charged
    /// once, for the committed bytes.
    DoubleFetch,
}

impl fmt::Display for DigestProvenance {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Advertised => "advertised",
            Self::DoubleFetch => "double-fetch",
        };
        formatter.write_str(label)
    }
}

/// One immutable result of one admitted download job at one version.
///
/// Refresh does not mutate; it siblings. A new snapshot for the same
/// `media_key` is a new row; the predecessor is queued for unlink
/// once the new snapshot is committed and integrity-checked.
///
/// Fields are private by design: the checked [`CommittedSnapshot::new`]
/// is the boundary that enforces the snapshot-path bound and the fixed
/// `[u8; 32]` digest shape, so every "Enforced by" claim about the
/// persisted row has a real call site.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommittedSnapshot {
    media_key: MediaKey,
    /// The durable source incarnation this snapshot was admitted against
    /// (`doc:202`, job-model table; `doc:157-168`, "Each source owns its
    /// offline decision" item 3). A source replacement supersedes the
    /// row's identity even though `SourceId` is preserved.
    source_incarnation: SourceIncarnationId,
    /// The accepted generation this snapshot was admitted against;
    /// process-local ordering only (`doc:203`, `doc:292-293`).
    capability_epoch: u64,
    /// Total committed byte count. Equal to the post-write `current_bytes`
    /// when the job reached `Committed`.
    byte_size: u64,
    /// SHA-256 of the bytes on disk, computed post-write and re-checked
    /// on resume. Fixed 32-byte digest — hex rendering is derived, never
    /// stored.
    sha256: [u8; 32],
    /// Which provenance tier supplied the expected digest this snapshot
    /// was verified against (`doc:1094-1112`).
    digest_provenance: DigestProvenance,
    /// The storage-engine-minted path inside the cache root. Opaque; no
    /// URL, credential, or credential-bearing parameter appears here.
    /// Bounded by [`MAX_OFFLINE_SNAPSHOT_PATH_BYTES`].
    cache_path: String,
    /// The licence state recorded at commit; for a declared licence this
    /// carries the persisted label only (`doc:190`, `doc:1150-1152`).
    licence: OperationalLicence,
    /// The committed-at epoch in seconds.
    committed_at_epoch_secs: u64,
}

impl CommittedSnapshot {
    /// Checked constructor for a committed row.
    ///
    /// Enforces the snapshot-path bound
    /// ([`MAX_OFFLINE_SNAPSHOT_PATH_BYTES`], via
    /// [`validate_snapshot_path_bytes`]) and takes the digest in its
    /// canonical `[u8; 32]` shape, so a committed row cannot exist with
    /// an unbounded path or a non-digest value.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        media_key: MediaKey,
        source_incarnation: SourceIncarnationId,
        capability_epoch: u64,
        byte_size: u64,
        sha256: [u8; 32],
        digest_provenance: DigestProvenance,
        cache_path: String,
        licence: OperationalLicence,
        committed_at_epoch_secs: u64,
    ) -> Result<Self, OfflineError> {
        validate_snapshot_path_bytes(cache_path.len())?;
        Ok(Self {
            media_key,
            source_incarnation,
            capability_epoch,
            byte_size,
            sha256,
            digest_provenance,
            cache_path,
            licence,
            committed_at_epoch_secs,
        })
    }

    pub fn media_key(&self) -> &MediaKey {
        &self.media_key
    }

    pub fn source_incarnation(&self) -> SourceIncarnationId {
        self.source_incarnation
    }

    pub fn capability_epoch(&self) -> u64 {
        self.capability_epoch
    }

    pub fn byte_size(&self) -> u64 {
        self.byte_size
    }

    pub fn sha256(&self) -> &[u8; 32] {
        &self.sha256
    }

    /// Lowercase hex rendering of the committed digest.
    pub fn sha256_hex(&self) -> String {
        const HEX: &[u8; 16] = b"0123456789abcdef";
        let mut encoded = String::with_capacity(self.sha256.len() * 2);
        for &byte in &self.sha256 {
            encoded.push(char::from(HEX[usize::from(byte >> 4)]));
            encoded.push(char::from(HEX[usize::from(byte & 0x0f)]));
        }
        encoded
    }

    pub fn digest_provenance(&self) -> DigestProvenance {
        self.digest_provenance
    }

    pub fn cache_path(&self) -> &str {
        &self.cache_path
    }

    pub fn licence(&self) -> &OperationalLicence {
        &self.licence
    }

    pub fn committed_at_epoch_secs(&self) -> u64 {
        self.committed_at_epoch_secs
    }
}

/// A live, in-flight download job. The engine owns one `JobRecord` per
/// `(media_key, source_incarnation)` and never admits a second while the
/// first is non-terminal (`doc:288-293`, "One job per
/// `(media_key, source_incarnation)`", rule 5).
///
/// Restart authorization compares the durable
/// `(SourceId, SourceIncarnationId)` pair — never a transient generation
/// number; `capability_epoch` only orders supersession within one
/// process run, and numeric equality is never authorization
/// (`doc:325-342`, "Authenticated, resumable download jobs").
///
/// The field set and types mirror the contract's job-model table at
/// `doc:199-211`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct JobRecord {
    pub media_key: MediaKey,
    /// Durable, non-secret identity of the owning source incarnation,
    /// recorded at admission (`doc:202`). Restart authorization compares
    /// this durable identity, never a transient generation number.
    pub source_incarnation: SourceIncarnationId,
    /// The source registry's accepted generation, process-local ordering
    /// only (`doc:203`); never restart-stable (`doc:292-293`).
    pub capability_epoch: u64,
    /// Server-advertised `Content-Length` when the response declares one;
    /// quota input only, never a committed size and never authoritative
    /// (`doc:204`). An over-cap declared total fails
    /// [`check_declared_total`] at admission.
    pub requested_bytes: Option<u64>,
    /// Entity validator captured from the first successful response.
    /// `Some` is required for any resumption; `None` disables resume
    /// and restricts the job to a full restart (`doc:205`).
    pub resume_validator: Option<EntityValidator>,
    pub current_bytes: u64,
    /// Progressively trusted only after the full file is received and
    /// re-checked post-write. `None` until the engine reaches `Verifying`;
    /// `Some(digest)` once a candidate digest has been computed and
    /// compared against the expected value.
    pub current_sha256: Option<[u8; 32]>,
    /// Durable bytes the job's journal and sidecar records occupy;
    /// engine-owned, charged against the same global quota as payload
    /// (`doc:208`, job-model table).
    pub journal_bytes: u64,
    pub state: JobState,
    /// Opaque lease reference of the in-flight HTTP request. Owned by the
    /// source registry; the engine treats it as identity and never inspects
    /// its payload.
    pub last_lease: Option<LeaseId>,
    /// Redacted, structured, terminal cause when `state = Failed`
    /// (`doc:211`).
    pub failure: Option<OfflineError>,
}

impl JobRecord {
    pub fn new(
        media_key: MediaKey,
        source_incarnation: SourceIncarnationId,
        capability_epoch: u64,
    ) -> Self {
        Self {
            media_key,
            source_incarnation,
            capability_epoch,
            requested_bytes: None,
            resume_validator: None,
            current_bytes: 0,
            current_sha256: None,
            journal_bytes: 0,
            state: JobState::Queued,
            last_lease: None,
            failure: None,
        }
    }
}

/// Opaque identifier of one accepted revocable lease. The engine treats
/// it as identity and never inspects its payload; the source registry is
/// the only authority that can mint, validate, or revoke a value.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct LeaseId(u64);

impl LeaseId {
    /// Adopt an already-minted lease identifier. Only the source registry
    /// calls this; the engine never invents a lease from raw integers.
    pub const fn from_raw(raw: u64) -> Self {
        Self(raw)
    }

    /// Internal accessor used by tests and by the source registry's
    /// adapter boundary. Never exposed through GTK, the catalogue reader,
    /// or the persisted cache row.
    pub const fn raw(self) -> u64 {
        self.0
    }
}

/// Resolve the offline catalogue read for one `(SourceId, TrackId)`
/// pair. The catalogue is read-only and never mints `SourceId` or
/// `TrackId` values; it only answers whether a committed snapshot is
/// available, returns its immutable record, or returns `None` to mean
/// "the live endpoint is the source of truth".
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OfflineCatalogueEntry {
    /// No cached snapshot is available; live playback is the source of
    /// truth.
    LiveOnly,
    /// A committed snapshot exists and is playable.
    Cached(CommittedSnapshot),
    /// A committed snapshot exists but its licence has been revoked.
    /// The file is preserved on disk; the row is not playable.
    Revoked(CommittedSnapshot),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::architecture::{SourceId, TrackId};
    use uuid::Uuid;

    fn fixture_media_key() -> MediaKey {
        MediaKey::new(SourceId::local(), TrackId::new("track-1").unwrap())
    }

    fn fixture_incarnation() -> SourceIncarnationId {
        SourceIncarnationId::from_uuid(Uuid::from_u128(0x1234_5678_9abc_def0_1234_5678_9abc_def0))
    }

    fn fixture_snapshot(cache_path: String) -> Result<CommittedSnapshot, OfflineError> {
        CommittedSnapshot::new(
            fixture_media_key(),
            fixture_incarnation(),
            1,
            4096,
            [0xab; 32],
            DigestProvenance::DoubleFetch,
            cache_path,
            OperationalLicence::SourceDeclared(
                LicenceLabel::new("subsonic-streaming-self").unwrap(),
            ),
            1_700_000_000,
        )
    }

    #[test]
    fn operational_licence_defaults_to_denied() {
        assert_eq!(OperationalLicence::default(), OperationalLicence::Denied);
    }

    #[test]
    fn job_state_is_terminal_only_for_committed_failed_cancelled() {
        for state in [
            JobState::Queued,
            JobState::Connecting,
            JobState::Receiving,
            JobState::Verifying,
            JobState::Committing,
        ] {
            assert!(!state.is_terminal(), "{state:?} must not be terminal");
        }
        for state in [JobState::Committed, JobState::Failed, JobState::Cancelled] {
            assert!(state.is_terminal(), "{state:?} must be terminal");
        }
    }

    #[test]
    fn offline_error_display_is_redacted() {
        // No variant name should leak a URL, status, header, body, or
        // credential — every display impl is the variant label only.
        let labels = [
            (OfflineError::Network, "network"),
            (OfflineError::AuthExpired, "auth-expired"),
            (OfflineError::LeaseRevoked, "lease-revoked"),
            (OfflineError::Denied, "denied"),
            (OfflineError::IntegrityMismatch, "integrity-mismatch"),
            (
                OfflineError::IntegrityUnverifiable,
                "integrity-unverifiable",
            ),
            (OfflineError::LicenceDenied, "licence-denied"),
            (OfflineError::QuotaExceeded, "quota-exceeded"),
            (
                OfflineError::PublishRetriesExhausted,
                "publish-retries-exhausted",
            ),
            (OfflineError::StorageUnavailable, "storage-unavailable"),
            (OfflineError::UnsupportedSource, "unsupported-source"),
        ];
        for (variant, label) in labels {
            let rendered = variant.to_string();
            assert_eq!(rendered, label, "{variant:?} label drifted");
            for forbidden in ["http://", "https://", "token=", "password=", "Bearer "] {
                assert!(
                    !rendered.contains(forbidden),
                    "{variant:?} leaked {forbidden:?} in display"
                );
            }
        }
    }

    #[test]
    fn offline_error_serde_round_trips_kebab_labels() {
        for (variant, label) in [
            (OfflineError::Network, "\"network\""),
            (OfflineError::AuthExpired, "\"auth-expired\""),
            (OfflineError::LeaseRevoked, "\"lease-revoked\""),
            (OfflineError::Denied, "\"denied\""),
            (OfflineError::IntegrityMismatch, "\"integrity-mismatch\""),
            (
                OfflineError::IntegrityUnverifiable,
                "\"integrity-unverifiable\"",
            ),
            (OfflineError::LicenceDenied, "\"licence-denied\""),
            (OfflineError::QuotaExceeded, "\"quota-exceeded\""),
            (
                OfflineError::PublishRetriesExhausted,
                "\"publish-retries-exhausted\"",
            ),
            (OfflineError::StorageUnavailable, "\"storage-unavailable\""),
            (OfflineError::UnsupportedSource, "\"unsupported-source\""),
        ] {
            let json = serde_json::to_string(&variant).expect("serialize");
            assert_eq!(json, label);
            let back: OfflineError = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(back, variant);
        }
    }

    #[test]
    fn declared_total_above_payload_cap_fails_quota_exceeded() {
        // Real audio payloads are megabytes; they must never be rejected
        // for being themselves.
        let cap: u64 = 256 * 1024 * 1024;
        assert_eq!(check_declared_total(5 * 1024 * 1024, cap), Ok(()));
        assert_eq!(check_declared_total(200 * 1024 * 1024, cap), Ok(()));
        // Equality passes: an exact-cap payload is not a quota failure.
        assert_eq!(check_declared_total(cap, cap), Ok(()));
        // Strictly above the cap fails QuotaExceeded before any network
        // work, including the u64::MAX pathological header.
        assert_eq!(
            check_declared_total(cap + 1, cap),
            Err(OfflineError::QuotaExceeded)
        );
        assert_eq!(
            check_declared_total(u64::MAX, cap),
            Err(OfflineError::QuotaExceeded)
        );
    }

    #[test]
    fn job_identity_is_media_key_and_source_incarnation() {
        let key = fixture_media_key();
        let first = JobRecord::new(key.clone(), fixture_incarnation(), 1);
        let second = JobRecord::new(
            key.clone(),
            SourceIncarnationId::from_uuid(Uuid::from_u128(
                0x9876_5432_10fe_dcba_9876_5432_10fe_dcba,
            )),
            1,
        );
        // Same media_key and capability_epoch, different durable
        // incarnation: the identity differs, exactly as the contract's
        // identity rule requires.
        assert_ne!(first.source_incarnation, second.source_incarnation);
        assert_eq!(first.capability_epoch, second.capability_epoch);
        assert_eq!(first.media_key, second.media_key);
        assert_ne!(first, second);
        // Defaults from the job-model table.
        assert_eq!(first.journal_bytes, 0);
        assert!(first.requested_bytes.is_none());
        assert!(first.resume_validator.is_none());
        assert!(first.current_sha256.is_none());
        assert!(first.last_lease.is_none());
        assert!(first.failure.is_none());
        assert_eq!(first.state, JobState::Queued);
    }

    #[test]
    fn media_key_round_trip_via_source_and_track_ids() {
        let key = MediaKey::new(SourceId::local(), TrackId::new("track-1").unwrap());
        let record = JobRecord::new(key.clone(), fixture_incarnation(), 1);
        assert_eq!(record.media_key, key);
        assert_eq!(record.state, JobState::Queued);
        assert_eq!(record.capability_epoch, 1);
        assert_eq!(record.source_incarnation, fixture_incarnation());
        assert!(record.failure.is_none());
        assert_eq!(record.current_bytes, 0);
        assert_eq!(record.journal_bytes, 0);
        assert!(record.requested_bytes.is_none());
        assert!(record.resume_validator.is_none());
        assert!(record.current_sha256.is_none());
        assert!(record.last_lease.is_none());
    }

    #[test]
    fn source_incarnation_id_is_opaque_serialisable_and_checked() {
        let id = fixture_incarnation();
        assert_eq!(id.as_uuid(), id.to_string().parse::<Uuid>().unwrap());
        let parsed: SourceIncarnationId = id.to_string().parse().expect("FromStr");
        assert_eq!(parsed, id);
        assert_ne!(SourceIncarnationId::random(), SourceIncarnationId::random());
        let json = serde_json::to_string(&id).expect("serialize");
        let back: SourceIncarnationId = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, id);
        assert!("not-a-uuid".parse::<SourceIncarnationId>().is_err());
    }

    #[test]
    fn entity_validator_bounds_redaction_and_serde() {
        // Bound, bound + 1, empty.
        let at_bound = EntityValidator::etag("x".repeat(MAX_OFFLINE_METADATA_BYTES))
            .expect("validator at bound");
        assert!(
            EntityValidator::etag("x".repeat(MAX_OFFLINE_METADATA_BYTES + 1)).is_none(),
            "over-bound validator must be discarded"
        );
        assert!(
            EntityValidator::etag("").is_none(),
            "empty must be discarded"
        );
        assert!(
            EntityValidator::last_modified("y".repeat(MAX_OFFLINE_METADATA_BYTES + 1)).is_none()
        );

        assert!(at_bound.is_strong());
        let last_modified =
            EntityValidator::last_modified("Wed, 21 Oct 2015 07:28:00 GMT").expect("validator");
        assert!(!last_modified.is_strong());
        assert_eq!(last_modified.kind(), "last-modified");
        assert_eq!(last_modified.value(), "Wed, 21 Oct 2015 07:28:00 GMT");

        // Redacted debug: kind + byte length, never the payload.
        let debug = format!("{at_bound:?}");
        assert!(debug.contains("etag"), "{debug}");
        assert!(debug.contains("byte_len"), "{debug}");
        assert!(!debug.contains("xxxx"), "{debug}");

        // Display label == serde variant label.
        assert_eq!(at_bound.to_string(), "etag");
        assert_eq!(last_modified.to_string(), "last-modified");
        let small = EntityValidator::etag("abc").expect("validator");
        assert_eq!(
            serde_json::to_string(&small).expect("serialize"),
            "{\"etag\":\"abc\"}"
        );
        let back: EntityValidator =
            serde_json::from_str("{\"etag\":\"abc\"}").expect("deserialize");
        assert_eq!(back, small);
        let back_lm: EntityValidator =
            serde_json::from_str("{\"last-modified\":\"Tue, 01 Sep 2026 00:00:00 GMT\"}")
                .expect("deserialize");
        assert_eq!(back_lm.kind(), "last-modified");
        // Serde rejection goes through the checked constructor.
        assert!(serde_json::from_str::<EntityValidator>("{\"etag\":\"\"}").is_err());
        let oversized = serde_json::json!({ "etag": "x".repeat(MAX_OFFLINE_METADATA_BYTES + 1) });
        assert!(serde_json::from_value::<EntityValidator>(oversized).is_err());
    }

    #[test]
    fn licence_label_bounds_redaction_and_serde() {
        let at_bound =
            LicenceLabel::new("x".repeat(MAX_OFFLINE_METADATA_BYTES)).expect("label at bound");
        assert_eq!(at_bound.as_str().len(), MAX_OFFLINE_METADATA_BYTES);
        assert!(LicenceLabel::new("x".repeat(MAX_OFFLINE_METADATA_BYTES + 1)).is_none());
        assert!(LicenceLabel::new("").is_none());

        let label = LicenceLabel::new("subsonic-streaming-self").expect("label");
        assert_eq!(label.as_str(), "subsonic-streaming-self");
        assert_eq!(label.to_string(), "subsonic-streaming-self");
        let debug = format!("{label:?}");
        assert!(debug.contains("byte_len"), "{debug}");
        assert!(!debug.contains("subsonic"), "{debug}");

        let json = serde_json::to_string(&label).expect("serialize");
        assert_eq!(json, "\"subsonic-streaming-self\"");
        let back: LicenceLabel = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, label);
        assert!(serde_json::from_str::<LicenceLabel>("\"\"").is_err());
        let oversized = serde_json::Value::String("x".repeat(MAX_OFFLINE_METADATA_BYTES + 1));
        assert!(serde_json::from_value::<LicenceLabel>(oversized).is_err());
    }

    #[test]
    fn operational_licence_serde_and_display() {
        let declared = OperationalLicence::SourceDeclared(
            LicenceLabel::new("jellyfin-streaming-self").unwrap(),
        );
        assert_eq!(
            serde_json::to_string(&OperationalLicence::Denied).unwrap(),
            "\"denied\""
        );
        assert_eq!(
            serde_json::to_string(&declared).unwrap(),
            "{\"source-declared\":\"jellyfin-streaming-self\"}"
        );
        assert_eq!(
            serde_json::to_string(&OperationalLicence::Revoked).unwrap(),
            "\"revoked\""
        );
        let back: OperationalLicence =
            serde_json::from_str("{\"source-declared\":\"plex-streaming-self\"}")
                .expect("deserialize");
        assert_eq!(
            back,
            OperationalLicence::SourceDeclared(LicenceLabel::new("plex-streaming-self").unwrap())
        );
        // Display renders the persisted label for SourceDeclared.
        assert_eq!(back.to_string(), "plex-streaming-self");
        assert_eq!(OperationalLicence::Denied.to_string(), "denied");
        assert_eq!(OperationalLicence::Revoked.to_string(), "revoked");
    }

    #[test]
    fn job_state_serde_matches_display() {
        for (state, label) in [
            (JobState::Queued, "queued"),
            (JobState::Connecting, "connecting"),
            (JobState::Receiving, "receiving"),
            (JobState::Verifying, "verifying"),
            (JobState::Committing, "committing"),
            (JobState::Committed, "committed"),
            (JobState::Failed, "failed"),
            (JobState::Cancelled, "cancelled"),
        ] {
            assert_eq!(state.to_string(), label);
            let json = serde_json::to_string(&state).expect("serialize");
            assert_eq!(json, format!("\"{label}\""));
            let back: JobState = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(back, state);
        }
    }

    #[test]
    fn digest_provenance_serde_matches_display() {
        for (provenance, label) in [
            (DigestProvenance::Advertised, "advertised"),
            (DigestProvenance::DoubleFetch, "double-fetch"),
        ] {
            assert_eq!(provenance.to_string(), label);
            let json = serde_json::to_string(&provenance).expect("serialize");
            assert_eq!(json, format!("\"{label}\""));
            let back: DigestProvenance = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(back, provenance);
        }
    }

    #[test]
    fn committed_snapshot_checked_constructor_enforces_path_bound() {
        let max_path = "c/".to_string() + &"a".repeat(MAX_OFFLINE_SNAPSHOT_PATH_BYTES - 2);
        assert_eq!(max_path.len(), MAX_OFFLINE_SNAPSHOT_PATH_BYTES);
        let at_bound = fixture_snapshot(max_path).expect("snapshot at path bound");
        assert_eq!(at_bound.media_key(), &fixture_media_key());
        assert_eq!(at_bound.source_incarnation(), fixture_incarnation());
        assert_eq!(at_bound.capability_epoch(), 1);
        assert_eq!(at_bound.byte_size(), 4096);
        assert_eq!(at_bound.sha256(), &[0xab; 32]);
        assert_eq!(at_bound.sha256_hex(), "ab".repeat(32));
        assert_eq!(at_bound.digest_provenance(), DigestProvenance::DoubleFetch);
        assert_eq!(at_bound.committed_at_epoch_secs(), 1_700_000_000);
        match at_bound.licence() {
            OperationalLicence::SourceDeclared(label) => {
                assert_eq!(label.as_str(), "subsonic-streaming-self");
            }
            other => panic!("unexpected licence {other:?}"),
        }

        let over_bound = "c/".to_string() + &"a".repeat(MAX_OFFLINE_SNAPSHOT_PATH_BYTES - 1);
        assert!(over_bound.len() > MAX_OFFLINE_SNAPSHOT_PATH_BYTES);
        assert_eq!(
            fixture_snapshot(over_bound),
            Err(OfflineError::StorageUnavailable)
        );
        // Direct validator contract (used by the constructor).
        assert_eq!(
            validate_snapshot_path_bytes(MAX_OFFLINE_SNAPSHOT_PATH_BYTES),
            Ok(())
        );
        assert_eq!(
            validate_snapshot_path_bytes(MAX_OFFLINE_SNAPSHOT_PATH_BYTES + 1),
            Err(OfflineError::StorageUnavailable)
        );
    }

    #[test]
    fn offline_catalogue_entries_construct_all_variants() {
        let live = OfflineCatalogueEntry::LiveOnly;
        let snapshot = fixture_snapshot("snapshots/ab".to_string()).expect("snapshot");
        let cached = OfflineCatalogueEntry::Cached(snapshot.clone());
        let revoked = OfflineCatalogueEntry::Revoked(snapshot);
        assert_eq!(live, OfflineCatalogueEntry::LiveOnly);
        match cached {
            OfflineCatalogueEntry::Cached(inner) => {
                assert_eq!(inner.sha256(), &[0xab; 32]);
            }
            other => panic!("unexpected entry {other:?}"),
        }
        match revoked {
            OfflineCatalogueEntry::Revoked(inner) => {
                assert_eq!(inner.cache_path(), "snapshots/ab");
            }
            other => panic!("unexpected entry {other:?}"),
        }
        // The capability holder keeps its constructor exercised too.
        let capability = OfflineSnapshot::new(64 * 1024 * 1024);
        assert_eq!(capability.source_byte_cap, 64 * 1024 * 1024);
    }

    #[test]
    fn lease_id_is_opaque_and_compares_by_raw() {
        let a = LeaseId::from_raw(7);
        let b = LeaseId::from_raw(7);
        let c = LeaseId::from_raw(8);
        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_eq!(a.raw(), 7);
    }
}
