//! Bounded download/cache contracts for offline media.
//!
//! These types implement the source-scoped offline media contract documented
//! in `docs/offline-media.md` (P3.1). The contract requires:
//!
//! - The download/cache engine never becomes a source of its own. Cached
//!   items are owned by an existing `Source` and identified by the same
//!   `(SourceId, TrackId)` pair used by live playback.
//! - Capabilities are default-deny; only the same authenticated backends
//!   that opt into live `ServerPlaylist` reads may opt into offline.
//! - Operational licence is checked both at admission and at offline
//!   rendering; revoked rows are retired but the file is preserved.
//! - Failures are typed (`OfflineError`), redacted (no URL, header value,
//!   body excerpt, or credential), and terminal — a failed row never
//!   becomes playable.
//!
//! These types are deliberately small and exhaustive: the engine module is
//! the only place that orchestrates jobs, the storage module is the only
//! place that touches the filesystem, and the quota module is the only
//! place that decides eviction. The catalog module is the read path that
//! resolves a `MediaKey` to either the live endpoint or the cached file.

use std::fmt;

use serde::{Deserialize, Serialize};

use super::identity::MediaKey;

/// Upper bound for the cached-file portion of a snapshot path. The path
/// itself is generated by the storage layer and never crosses this layer
/// unencrypted, but the contract still bounds the persisted identifier
/// that the storage layer mints. Enforced by
/// [`validate_snapshot_path_bytes`].
pub const MAX_OFFLINE_SNAPSHOT_PATH_BYTES: usize = 4 * 1024;

/// Upper bound for a server-advertised `Content-Length` (or
/// `requested_bytes`) hint. The byte hint is metadata that the engine
/// trusts only as a quota input, not as a committed size, so the bound
/// is small (4 KiB) — well below any real audio payload and small
/// enough that a mis-sized or hostile header cannot inflate the
/// persisted row. Enforced by [`validate_byte_hint`].
pub const MAX_OFFLINE_BYTE_HINT: u64 = 4 * 1024;

/// Reject a server-advertised `Content-Length` (or equivalent
/// `requested_bytes`) hint that exceeds [`MAX_OFFLINE_BYTE_HINT`].
///
/// The hint is metadata, not a committed size: a payload above this
/// ceiling is treated as malformed input rather than as a quota
/// overrun. The engine surfaces the rejection as
/// [`OfflineError::StorageUnavailable`] because the source supplied a
/// byte count the cache layer cannot trust.
pub const fn validate_byte_hint(hint: u64) -> Result<(), OfflineError> {
    if hint <= MAX_OFFLINE_BYTE_HINT {
        Ok(())
    } else {
        Err(OfflineError::StorageUnavailable)
    }
}

/// Reject a storage-engine-minted snapshot path whose byte length
/// exceeds [`MAX_OFFLINE_SNAPSHOT_PATH_BYTES`]. The engine never
/// constructs the path; this is the contract the storage layer must
/// honour when minting one.
pub const fn validate_snapshot_path_bytes(byte_len: usize) -> Result<(), OfflineError> {
    if byte_len <= MAX_OFFLINE_SNAPSHOT_PATH_BYTES {
        Ok(())
    } else {
        Err(OfflineError::StorageUnavailable)
    }
}

/// Exact operational licence a source declares for offline replay of its
/// content. Default is `Denied`; a source must explicitly opt in.
///
/// The label is a short bounded identifier supplied by the source
/// (e.g. `subsonic-streaming-self`). It is never a free-form text field,
/// never the full licence text, and never the URL of the licence page.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum OperationalLicence {
    /// Default. A cached row may exist structurally but cannot become
    /// playable. Visible to GTK as "Offline unavailable" for that source.
    #[default]
    Denied,
    /// The source declares a contract that allows offline replay of its
    /// content for the user. The label is the only thing persisted.
    SourceDeclared,
    /// The source or backend has changed the licence after a row was
    /// committed. Visible as "Licence revoked"; the row is retired but
    /// the file is preserved.
    Revoked,
}

impl fmt::Display for OperationalLicence {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Denied => "denied",
            Self::SourceDeclared => "declared",
            Self::Revoked => "revoked",
        };
        formatter.write_str(label)
    }
}

/// The byte-cap holder a backend returns inside an admitted offline
/// capability. The cap is a per-source upper bound on the total bytes
/// the cache will commit for that source; the global quota layer still
/// bounds every committed row, so this cap is advisory at admission
/// time and authoritative only within the source.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OfflineSnapshot {
    /// Per-source byte total bounded at the source-adapter-declared cap.
    pub source_byte_cap: u64,
}

impl OfflineSnapshot {
    /// Construct a snapshot capability with the supplied byte cap. The
    /// cap is a source-adapter-declared upper bound; the engine still
    /// caps every committed row by the global quota.
    pub fn new(source_byte_cap: u64) -> Self {
        Self { source_byte_cap }
    }
}

/// State of one admitted download job. `Queued` through `Committed` are
/// transient or terminal-success; `Failed` and `Cancelled` are
/// terminal-failure states. The transitions are strictly monotonic — a
/// job never re-enters `Queued` from a later state.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum JobState {
    #[default]
    Queued,
    Connecting,
    Receiving,
    Verifying,
    Committing,
    Committed,
    Failed,
    Cancelled,
}

impl JobState {
    /// Whether this state is terminal. A terminal state never advances
    /// again; the engine records it and releases the lease.
    pub fn is_terminal(self) -> bool {
        matches!(self, Self::Committed | Self::Failed | Self::Cancelled)
    }
}

impl fmt::Display for JobState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Queued => "queued",
            Self::Connecting => "connecting",
            Self::Receiving => "receiving",
            Self::Verifying => "verifying",
            Self::Committing => "committing",
            Self::Committed => "committed",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
        };
        formatter.write_str(label)
    }
}

/// Structured, terminal cause of a failed or cancelled download.
///
/// Every variant is a fixed category. The variant name, and the variant
/// name only, is what the cache rows, GTK, the journal logs, and the
/// redacted failure messages ever expose. No raw HTTP status, redirect
/// path, body excerpt, header value, URL parameter, or credential
/// appears in the failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum OfflineError {
    /// Transient network failure that did not yet exhaust the resume
    /// budget. The engine retries on the same job.
    Network,
    /// The source's credential expired or was revoked mid-download.
    /// The lease is revoked; the cache row is not promoted. The user
    /// reauthenticates through the source's normal path.
    AuthExpired,
    /// The lease was revoked by the source lifecycle before commit.
    LeaseRevoked,
    /// The post-write SHA-256 of the bytes on disk did not match the
    /// server-advertised digest. Terminal; the temp file is unlinked.
    IntegrityMismatch,
    /// The source declared `OperationalLicence::Denied` or `Revoked` at
    /// admission. The job is refused before any network work.
    LicenceDenied,
    /// The global quota was exceeded before commit. The temp file is
    /// unlinked; no cache row is created.
    QuotaExceeded,
    /// The filesystem refused the temp reservation or the rename.
    StorageUnavailable,
    /// The source does not support offline; the engine refused
    /// admission. A backend that returns [`OfflineCapability::None`]
    /// from `offline_capability` never enters this state — only a
    /// backend that explicitly opted in and later declined does.
    UnsupportedSource,
    /// User-driven cancel, lifecycle supersession, or shutdown. The temp
    /// file is unlinked; no cache row is created.
    Cancelled,
}

impl fmt::Display for OfflineError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Network => "network",
            Self::AuthExpired => "auth-expired",
            Self::LeaseRevoked => "lease-revoked",
            Self::IntegrityMismatch => "integrity-mismatch",
            Self::LicenceDenied => "licence-denied",
            Self::QuotaExceeded => "quota-exceeded",
            Self::StorageUnavailable => "storage-unavailable",
            Self::UnsupportedSource => "unsupported-source",
            Self::Cancelled => "cancelled",
        };
        formatter.write_str(label)
    }
}

/// One immutable result of one admitted download job at one version.
///
/// Refresh does not mutate; it siblings. A new snapshot for the same
/// `media_key` is a new row; the predecessor is queued for unlink
/// once the new snapshot is committed and integrity-checked.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommittedSnapshot {
    pub media_key: MediaKey,
    /// The accepted generation this snapshot was admitted against.
    pub capability_epoch: u64,
    /// Total committed byte count. Equal to the post-write `current_bytes`
    /// when the job reached `Committed`.
    pub byte_size: u64,
    /// SHA-256 of the bytes on disk, computed post-write and re-checked
    /// on resume. Hex-encoded, lowercase.
    pub sha256_hex: String,
    /// The storage-engine-minted path inside the cache root. Opaque; no
    /// URL, credential, or credential-bearing parameter appears here.
    pub cache_path: String,
    /// The licence label that authorised the commit.
    pub licence_label: OperationalLicence,
    /// The committed-at epoch in seconds.
    pub committed_at_epoch_secs: u64,
}

/// A live, in-flight download job. The engine owns one `JobRecord` per
/// `(media_key, capability_epoch)` and never admits a second while the
/// first is non-terminal.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct JobRecord {
    pub media_key: MediaKey,
    pub capability_epoch: u64,
    pub requested_bytes: Option<u64>,
    pub current_bytes: u64,
    /// Progressively trusted only after the full file is received and
    /// re-checked post-write. `None` until the engine reaches `Verifying`;
    /// `Some(digest)` once a candidate digest has been computed and
    /// compared against the server-advertised value.
    pub current_sha256: Option<[u8; 32]>,
    pub state: JobState,
    /// Opaque lease reference of the in-flight HTTP request. Owned by the
    /// source registry; the engine treats it as identity and never inspects
    /// its payload.
    pub last_lease: Option<LeaseId>,
    pub failure: Option<OfflineError>,
}

impl JobRecord {
    pub fn new(media_key: MediaKey, capability_epoch: u64) -> Self {
        Self {
            media_key,
            capability_epoch,
            requested_bytes: None,
            current_bytes: 0,
            current_sha256: None,
            state: JobState::Queued,
            last_lease: None,
            failure: None,
        }
    }
}

/// Opaque identifier of one accepted revocable lease. The engine treats
/// it as identity and never inspects its payload; the source registry is
/// the only authority that can mint, validate, or revoke a value.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct LeaseId(u64);

impl LeaseId {
    /// Adopt an already-minted lease identifier. Only the source registry
    /// calls this; the engine never invents a lease from raw integers.
    pub const fn from_raw(raw: u64) -> Self {
        Self(raw)
    }

    /// Internal accessor used by tests and by the source registry's
    /// adapter boundary. Never exposed through GTK, the catalogue reader,
    /// or the persisted cache row.
    pub const fn raw(self) -> u64 {
        self.0
    }
}

/// Resolve the offline catalogue read for one `(SourceId, TrackId)`
/// pair. The catalogue is read-only and never mints `SourceId` or
/// `TrackId` values; it only answers whether a committed snapshot is
/// available, returns its immutable record, or returns `None` to mean
/// "the live endpoint is the source of truth".
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OfflineCatalogueEntry {
    /// No cached snapshot is available; live playback is the source of
    /// truth.
    LiveOnly,
    /// A committed snapshot exists and is playable.
    Cached(CommittedSnapshot),
    /// A committed snapshot exists but its licence has been revoked.
    /// The file is preserved on disk; the row is not playable.
    Revoked(CommittedSnapshot),
}

/// A single source's offline capability decision. Default-deny at every
/// layer — a source that does not declare returns [`OfflineCapability::None`]
/// from [`MediaBackend::offline_capability`](super::backend::MediaBackend::offline_capability),
/// and the engine never opens a job for it. A source that explicitly
/// refuses offline returns [`OfflineCapability::Denied`], which is
/// structurally distinct from `None` so the engine can surface
/// [`OfflineError::UnsupportedSource`] to GTK. Only the same set of
/// backends that opt into live `ServerPlaylist`-style read authority
/// (Subsonic, Jellyfin, Plex, DAAP) may opt in here; Radio-Browser,
/// removable, external-file, and the built-in local source must remain
/// `None` because they are not credentialed, are already local, or are
/// lifecycle-bound without a credential lane.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OfflineCapability {
    /// The source has not declared any offline capability. Local files,
    /// removable volumes, external-file sessions, and Radio-Browser
    /// return this and never enter the offline cache.
    None,
    /// The source has explicitly declined offline. Distinct from `None`
    /// so the engine can emit a structured `UnsupportedSource` reason.
    Denied,
    /// The source has admitted an offline capability with the supplied
    /// snapshot.
    Allowed(OfflineSnapshot),
}

impl OfflineCapability {
    /// Default-deny constructor. Backends that do not implement
    /// `offline_capability` return this.
    pub fn default_deny() -> Self {
        Self::None
    }
}

/// Well-known licence labels. The application never invents licence
/// labels — it only carries the ones the source adapter publishes.
pub mod licence_labels {
    /// Reserved for sources that have not opted in. The default.
    pub const DENIED: &str = "denied";
    /// A label Subsonic adapters emit for self-hosted streaming servers.
    pub const SUBSONIC_STREAMING_SELF: &str = "subsonic-streaming-self";
    /// A label Jellyfin adapters emit for self-hosted instances.
    pub const JELLYFIN_STREAMING_SELF: &str = "jellyfin-streaming-self";
    /// A label Plex adapters emit for self-hosted servers.
    pub const PLEX_STREAMING_SELF: &str = "plex-streaming-self";
    /// A label DAAP adapters emit for iTunes-style sharing.
    pub const DAAP_STREAMING_SELF: &str = "daap-streaming-self";
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::architecture::{SourceId, TrackId};

    #[test]
    fn operational_licence_defaults_to_denied() {
        assert_eq!(OperationalLicence::default(), OperationalLicence::Denied);
    }

    #[test]
    fn job_state_is_terminal_only_for_committed_failed_cancelled() {
        for state in [
            JobState::Queued,
            JobState::Connecting,
            JobState::Receiving,
            JobState::Verifying,
            JobState::Committing,
        ] {
            assert!(!state.is_terminal(), "{state:?} must not be terminal");
        }
        for state in [JobState::Committed, JobState::Failed, JobState::Cancelled] {
            assert!(state.is_terminal(), "{state:?} must be terminal");
        }
    }

    #[test]
    fn offline_error_display_is_redacted() {
        // No variant name should leak a URL, status, header, body, or
        // credential — every display impl is the variant name only.
        for variant in [
            OfflineError::Network,
            OfflineError::AuthExpired,
            OfflineError::LeaseRevoked,
            OfflineError::IntegrityMismatch,
            OfflineError::LicenceDenied,
            OfflineError::QuotaExceeded,
            OfflineError::StorageUnavailable,
            OfflineError::UnsupportedSource,
            OfflineError::Cancelled,
        ] {
            let rendered = variant.to_string();
            for forbidden in ["http://", "https://", "token=", "password=", "Bearer "] {
                assert!(
                    !rendered.contains(forbidden),
                    "{variant:?} leaked {forbidden:?} in display"
                );
            }
        }
    }

    #[test]
    fn offline_capability_default_is_none() {
        assert_eq!(OfflineCapability::default_deny(), OfflineCapability::None);
    }

    #[test]
    fn media_key_round_trip_via_source_and_track_ids() {
        let key = MediaKey::new(SourceId::local(), TrackId::new("track-1").unwrap());
        let record = JobRecord::new(key.clone(), 1);
        assert_eq!(record.media_key, key);
        assert_eq!(record.state, JobState::Queued);
        assert_eq!(record.capability_epoch, 1);
        assert!(record.failure.is_none());
        assert_eq!(record.current_bytes, 0);
        assert!(record.requested_bytes.is_none());
        assert!(record.current_sha256.is_none());
        assert!(record.last_lease.is_none());
    }

    #[test]
    fn lease_id_is_opaque_and_compares_by_raw() {
        let a = LeaseId::from_raw(7);
        let b = LeaseId::from_raw(7);
        let c = LeaseId::from_raw(8);
        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_eq!(a.raw(), 7);
    }
}
